// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Astronaut struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	IsPilot bool   `json:"isPilot"`
}

type Mission struct {
	ID   string       `json:"id"`
	Name string       `json:"name"`
	Crew []*Astronaut `json:"crew"`
}

type NewAstronaut struct {
	Name    string `json:"name"`
	IsPilot bool   `json:"isPilot"`
}
